name="Bouncer"
short_name="bouncer"
image="./bouncer.png"

[[features]]
kind="Either"
x=0
y=0
w=349
h=340
margin_left=10
margin_top=10
font_size=40

[[features]]
kind="Either"
x=0
y=340
w=349
h=340
margin_left=10
margin_top=10
font_size=40

