name="Brain Expansion"
short_name="brain"
image="brain.jpg"
[[features]]
kind="Text"
x=15
y=0
w=400
h=280
font_size=35
[[features]]
kind="Text"
x=15
y=300
w=400
h=280
font_size=35
[[features]]
kind="Text"
x=15
y=625
w=400
h=260
font_size=35
[[features]]
kind="Text"
x=15
y=900
w=400
h=300
font_size=35
