name="Patrig"
short_name="patrig"
image="./patrig.png"
[[features]]
w=503
h=462
x=556
y=20
kind="Either"
font_size=50
[[features]]
w=503
h=432
x=556
y=522
kind="Either"
font_size=50
[[features]]
w=503
h=462
x=556
y=981
kind="Either"
font_size=50
