name="Who Would Win"
short_name="whowouldwin"
image="./whowouldwin.png"
[[features]]
kind="Image"
x=20
y=90
w=216
h=216
[[features]]
kind="Text"
x=20
y=311
w=216
h=43
font_size=43
alignment="Center"

[[features]]
kind="Image"
x=276
y=90
w=216
h=216
[[features]]
kind="Text"
x=276
y=311
w=216
h=43
font_size=43
alignment="Center"
